### PR TITLE
Updating drupal-patchfile source and git_ref until PR is merged for f…

### PR DESCRIPTION
**Pull request by sk33lz**
…ix for D8.

**To Test**

- [ ] Checkout drush-patchfile-patch branch on your VM or build a new VM from this branch.

- [ ] Provision your VM.

- [ ] Do a `drush ps` inside of a Drupal 8.2.x fresh site install that has a valid patches.make file. ([This bear PR](https://github.com/zivtech/bear/pull/210) will work great for this test and can kill 2 PRs with one review.)

### CODE REVIEW

**Comment by lliss** [comment]
We really need a note about which PR. I don't want to get stuck on that fork forever.

**Comment by lliss** [comment]
@tizzo or @kleinmp either of you have an opinion on this?

**Comment by tizzo** [comment]
I'm fine with running on a branch from a PR but we definitely need to know what it is and why we're running it so we can move when it's merged.

I'm not sure @davereid is actively maintaining patchfile anymore - maybe it needs to be adopted - I wonder if he'd like a comaintainer… Dave?

**Comment by davereid** [comment]
I don't even know which PR this is referring to, there is no link. I've been making merges recently and reviewing the code, so yes it is active.

**Comment by davereid** [comment]
https://bitbucket.org/davereid/drush-patchfile/pull-requests/13/devide-between-drupal-7-and-drupal-8-way/diff seems to be the biggest one, which has already been merged into master?

**Comment by lliss** [comment]
@sk33lz Can you check this out. Looks like we may not need the PR at all anymore.

**Comment by sk33lz** [comment]
Yeah it looks like @davereid has merged this fork's changes at this point in the PR he linked. Here is the original commit we were using, https://bitbucket.org/szeidler/drush-patchfile/src/25ccc3683a32da867126a6e17e21524d9b054151?at=issue-31-d8-filename. Closing this out.

**Comment by sk33lz** [comment]
I've opened a new PR to change to the latest commit for drush-patchfile instead here, https://github.com/zivtech/vagrant-development-vm/pull/35.

**Comment by tizzo** [comment]
@davereid So sorry to imply that you weren't on top of things when you totally were! I had looked at the :octocat: and drupal.org mirrors and saw no updates for a couple of years - I didn't realize new releases weren't going out to d.o.  Totally my bad.

Thanks! You continue to be one of our Super Drupal Heroes.

**Pull request closed without merging**
