### PR TITLE
Update zivtech modules.

### PR DESCRIPTION
**Pull request by lliss**
This updates the puppetfile.lock to ensure the newest version of
zivtech controlled puppet modules are in place.

### To test:
 - Provision a new VM and ensure that puppet runs successfully.

### CODE REVIEW

**Comment by lliss** [comment]
@tizzo Since @sk33lz is out, can you take a look at this. It should ensure we can provision new VMs which was not the case when I was working with @alioso last week.

**Comment by lliss** [comment]
Any chance we can get this merged in soon?

**Comment by tizzo** [comment]
One thing to note - vagrant-librarian-puppet appears to be busted with vagrant 1.8.x currently and the issue queue seems pretty empty - so people either need to install librarian-puppet locally and manually or downgrade vagrant. :-/

**Comment by lliss** [comment]
I think we've been telling people to stay on 1.7.x for vagrant because librarian puppet had been an issue with 1.8 at least since I started.

**Comment by tizzo** [comment]
We should probably look into fixing it. "Just don't upgrade" is not a good
long term plan.

**Pull request merged**
