### PR TITLE
Updating drush-patchfile to latest commit.

### PR DESCRIPTION
**Pull request by sk33lz**

### CODE REVIEW

**Comment by sk33lz** [comment]
I'm getting some odd results when testing this on my local. I'm not sure if it's my puppet version or what.

I'm running:

- Puppet 3.8.6

- Vagrant 1.8.7

- VirtualBox 5.1.12 r112440

- Drush 8.1.8

First I get this error very early in the provisioning process during `vagrant up`.

```
==> default: Warning: Scope(Concat::Fragment[drush-config-fetcher-php-tag]): The $ensure parameter to concat::fragment is deprecated and has no effect.
==> default: Warning: Scope(Concat::Fragment[drush-config-patch-file-php-tag]): The $ensure parameter to concat::fragment is deprecated and has no effect.
```

Then I get the following later on.

```
==> default: Error: Could not set 'file' on ensure: No such file or directory - /etc/drush/conf.d/patch-file.php20170110-1663-vxc1sk.lock
==> default: Error: Could not set 'file' on ensure: No such file or directory - /etc/drush/conf.d/patch-file.php20170110-1663-vxc1sk.lock
==> default: Wrapped exception:
==> default: No such file or directory - /etc/drush/conf.d/patch-file.php20170110-1663-vxc1sk.lock
==> default: Error: /Stage[main]/Drush/Drush::Config[patch-file]/Concat[/etc/drush/conf.d/patch-file.php]/File[/etc/drush/conf.d/patch-file.php]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /etc/drush/conf.d/patch-file.php20170110-1663-vxc1sk.lock
```

It appears to be related to this line in our puppet-drush module, https://github.com/zivtech/puppet-drush/blob/master/manifests/config.pp#L40.

Oddly enough, if I `vagrant provision` right after that these errors go away and everything provisions normally.

**Comment by lliss** [comment]
Still relevant? Close if not.

**Comment by sk33lz** [comment]
This is still legit. We are running on a version from 2014 currently.

**Comment by lliss** [comment]
Cool. Fix up and then let's commit it.

**Comment by sk33lz** [comment]
Trying to get there heh.

**Comment by sk33lz** [comment]
Doh, that file doesn't exist anymore to rebase against. I need to move this change to `hieradata/common.yaml`.

**Pull request merged**
