### PR TITLE
Install Pantheon's terminus via composer

### PR DESCRIPTION
**Pull request by tizzo**
[Terminus](https://github.com/pantheon-systems/terminus) is the CLI interface to Pantheon's stuff. This change [installs terminus via composer](https://pantheon.io/docs/terminus/).

Thoughts @lliss @sk33lz @AllieRays?

### CODE REVIEW

**Comment by lliss** [comment]
I have fears about adding something to the dev vm that allows you direct access to the live site or database, but I think in general this is a nice feature.

**Comment by tizzo** [comment]
Well, you'd still have to log in to pantheon, explicitly export the aliases list, then use those aliases.

**Comment by lliss** [comment]
Sure, I just find it to be a little safer to prevent a dev machine from being able do jump to a live site and do things. I'm not saying that it is necessarily error prone but it does make it easier to do something silly.

**Comment by tizzo** [comment]
That's also true of SSH access and arguably fetcher (if you have a prod env you can fetch from there).

Bump - @lliss any chance we can decide to close this or else merge it?

**Comment by tizzo** [comment]
@sk33lz @lliss bump

**Comment by sk33lz** [comment]
I've used it before to access Pantheon sites, so I'm game for adding it in.

**Comment by lliss** [comment]
I'll take it for a spin. Stay tuned.

**Comment by lliss** [comment]
+1.

**Pull request merged**
