### PR TITLE
Updating default hostname to vm instead of local to help front end de…

### PR DESCRIPTION
**Pull request by sk33lz**
…v debugging.

### CODE REVIEW

**Comment by alioso** [comment]
The reason for doing this is that when using browsersync for our development, we need to proxy the vm and the .local address is used by the native Bonjour app on OSX, making browsersync barely usable.

**Comment by lliss** [comment]
@sk33lz Need to up date the Readme as well. Also, we should take @alioso's comment above and add it to the commit message. It is a good idea to explain why the change actually is needed.

**Comment by sk33lz** [comment]
Good call. I'll update it in a few.

**Comment by tizzo** [comment]
We should make a new issue for switching to `local.zivtech.com` which we can create a proper a record (or cname?) for.

**Pull request merged**
