### PR TITLE
Use mailhog rather than custom mail handler.

### PR DESCRIPTION
**Pull request by lliss**
Mailhog and the associated mhsendmail can are used to catch mail
sent from the machine and allow the messages to be viewed in the
browser in a nice UI. Here we replace sendmail with mhsendmail
and ensure mailhog is running via systemd.

- Remove the older mail override method
- Update readme
- Adjust puppet dependencies so we don't rely on multiple PHP
  versions.

## To test
- run `vagrant provision` on the vm and ensure there are no errors.
- Use a site that sends mail to send a message.
- visit mailhog.local.zivtech.com:8025 (actually *.local.zivtech.com:8025 will work)
- Ensure you see the email message arrive.

### CODE REVIEW

**Comment by sk33lz** [comment]
Provisioning this now locally for testing.

**Comment by sk33lz** [comment]
I cannot get the VM to provision properly on my local at all... Getting some weird vagrant errors...

**Comment by lliss** [comment]
Such as?

**Comment by sk33lz** [comment]
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 'enp0s8' || true
/sbin/ip addr flush dev 'enp0s8'
/sbin/ifdown 'enp0s9' || true
/sbin/ip addr flush dev 'enp0s9'
# Remove any previous network modifications from the interfaces file
sed -e '/^#VAGRANT-BEGIN/,$ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces.pre
sed -ne '/^#VAGRANT-END/,$ p' /etc/network/interfaces | tac | sed -e '/^#VAGRANT-END/,$ d' | tac > /tmp/vagrant-network-interfaces.post

cat \
  /tmp/vagrant-network-interfaces.pre \
  /tmp/vagrant-network-entry \
  /tmp/vagrant-network-interfaces.post \
  > /etc/network/interfaces

rm -f /tmp/vagrant-network-interfaces.pre
rm -f /tmp/vagrant-network-entry
rm -f /tmp/vagrant-network-interfaces.post

/sbin/ifup 'enp0s8'
/sbin/ifup 'enp0s9'

Stdout from the command:

Waiting for DAD... Timed out
Failed to bring up enp0s9.


Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
/sbin/ifdown: interface enp0s9 not configured
```

**Comment by jkaeser** [comment]
> `Waiting for DAD... Timed out`

This is so sad...

**Comment by sk33lz** [comment]
I saw there were some additional commits, so I re-ran after those to see if they would fix the issue, but I'm still getting the same set of errors. I'm going to delete the repo completely and try again.

**Comment by lliss** [comment]
Shouldn't need to delete the repo, just the vm.

**Comment by sk33lz** [comment]
I've tried both for good measure and end up with the same error. I was building a bunch of other things and testing a bunch of composer install config today so I didn't want to reboot. I'm going to try rebooting my mac tomorrow morning before I get started and see if that resolves the error...

**Comment by lliss** [comment]
I tried this on master and have the same issue so it seems to be something unrelated to this change.

**Comment by sk33lz** [comment]
A reboot fixed my SSH error and once I was able to provision the box I had to remove the prefork apache modules with the following commands:

```
a2dismod mpm_prefork
a2dismod php7.0
```
After removing those modules I was able to reprovision without errors. 

Once is was up, I still couldn't access mailhog at the URL you provided. I had to start the mailhog service manually to get it to respond at that URL.

**Comment by lliss** [comment]
Additionally, fixes the issue that was the underlying reason for https://github.com/zivtech/vagrant-development-vm/pull/43

**Pull request merged**
